// ProjectGenerator.swift
// Core project scaffolding engine

import Foundation

/// Generates a complete project from a template and configuration
actor ProjectGenerator {
    private let fileManager = FileManager.default
    private let templateEngine: TemplateEngine

    init() {
        self.templateEngine = TemplateEngine()
    }

    /// Generates a project at the specified path
    func generate(projectName: String, config: ProjectConfig, outputPath: String?) async throws {
        let destination = resolveDestination(projectName: projectName, outputPath: outputPath)

        // Validate destination
        guard !fileManager.fileExists(atPath: destination.path) else {
            throw GenerationError.destinationExists(destination.path)
        }

        // Create directory structure
        try createDirectoryStructure(at: destination, config: config)

        // Generate core files
        try await generatePackageManifest(at: destination, config: config)
        try await generateSourceStructure(at: destination, config: config)
        try await generateTestStructure(at: destination, config: config)

        // Generate enforcement layer
        if config.enableAccessibility {
            try await generateAccessibilityEnforcement(at: destination, config: config)
        }

        if config.enableLocalization {
            try await generateLocalizationInfrastructure(at: destination, config: config)
        }

        // Generate workflow files
        try await generateGitHooks(at: destination, config: config)
        try await generateCIWorkflows(at: destination, config: config)

        // Generate documentation registry
        try await generateDocumentationRegistry(at: destination, config: config)

        // Generate immunity system
        if config.enableImmunity {
            try await generateImmunityConfig(at: destination, config: config)
        }

        // Generate AGENTS.md
        try await generateAgentsMD(at: destination, config: config)
    }

    // MARK: - Private Helpers

    private func resolveDestination(projectName: String, outputPath: String?) -> URL {
        let basePath = outputPath ?? fileManager.currentDirectoryPath
        return URL(fileURLWithPath: basePath).appendingPathComponent(projectName)
    }

    private func createDirectoryStructure(at destination: URL, config: ProjectConfig) throws {
        var directories = [
            "Sources/\(config.projectName)",
            "Sources/\(config.projectName)/Models",
            "Sources/\(config.projectName)/ViewModels",
            "Sources/\(config.projectName)/Views",
            "Sources/\(config.projectName)/Services",
            "Sources/\(config.projectName)/Utilities",
            "Tests/\(config.projectName)Tests",
            "Documentation",
            ".foundation",
        ]

        if config.isMacOSApp {
            directories.append("Sources/\(config.projectName)/MenuBar")
            directories.append("Sources/\(config.projectName)/Settings")
        } else {
            directories.append("Tests/\(config.projectName)UITests")
        }

        for dir in directories {
            let url = destination.appendingPathComponent(dir)
            try fileManager.createDirectory(at: url, withIntermediateDirectories: true)
        }
    }

    private func generatePackageManifest(at destination: URL, config: ProjectConfig) async throws {
        let manifest: String
        if config.isMacOSApp {
            manifest = """
            // swift-tools-version: 6.3
            // \(config.projectName) — Generated by SwiftAnvil

            import PackageDescription

            let package = Package(
                name: "\(config.projectName)",
                platforms: [.macOS(.v15)],
                products: [
                    .library(
                        name: "\(config.projectName)",
                        targets: ["\(config.projectName)"]
                    ),
                ],
                dependencies: [
                    .package(url: "https://github.com/swiftanvil/swiftanvil-anvil-network.git", from: "1.0.0"),
                    .package(url: "https://github.com/swiftanvil/swiftanvil-anvil-flags.git", from: "1.0.0"),
                    // TODO: Enable when Phase 8.2–8.4 packages are published
                    // .package(url: "https://github.com/swiftanvil/swiftanvil-anvil-settings.git", branch: "main"),
                    // .package(url: "https://github.com/swiftanvil/swiftanvil-anvil-menubar.git", branch: "main"),
                    // .package(url: "https://github.com/swiftanvil/swiftanvil-anvil-window.git", branch: "main"),
                ],
                targets: [
                    .target(
                        name: "\(config.projectName)",
                        dependencies: [
                            .product(name: "AnvilNetwork", package: "swiftanvil-anvil-network"),
                            .product(name: "AnvilFlags", package: "swiftanvil-anvil-flags"),
                        ]
                    ),
                    .testTarget(
                        name: "\(config.projectName)Tests",
                        dependencies: ["\(config.projectName)"]
                    ),
                ],
                swiftLanguageModes: [.v6]
            )
            """
        } else {
            manifest = """
            // swift-tools-version: 6.3
            // \(config.projectName) — Generated by SwiftAnvil

            import PackageDescription

            let package = Package(
                name: "\(config.projectName)",
                platforms: [
                    .iOS(.v\(config.minimumOSVersion?.replacingOccurrences(of: ".", with: "_") ?? "17")),
                    .macOS(.v14)
                ],
                products: [
                    .library(
                        name: "\(config.projectName)",
                        targets: ["\(config.projectName)"]
                    ),
                ],
                dependencies: [],
                targets: [
                    .target(
                        name: "\(config.projectName)",
                        dependencies: []
                    ),
                    .testTarget(
                        name: "\(config.projectName)Tests",
                        dependencies: ["\(config.projectName)"]
                    ),
                ],
                swiftLanguageModes: [.v6]
            )
            """
        }

        let path = destination.appendingPathComponent("Package.swift")
        try manifest.write(to: path, atomically: true, encoding: .utf8)
    }

    private func generateSourceStructure(at destination: URL, config: ProjectConfig) async throws {
        if config.isMacOSApp {
            try await generateMacOSSourceStructure(at: destination, config: config)
        } else {
            try generateIOSSourceStructure(at: destination, config: config)
        }
    }

    private func generateMacOSSourceStructure(at destination: URL, config: ProjectConfig) async throws {
        let appFile = """
        import SwiftUI

        @main
        struct \(config.projectName)App: App {
            @State private var viewModel = AppViewModel()

            var body: some Scene {
                WindowGroup {
                    ContentView()
                        .environment(viewModel)
                }

                MenuBarExtra("\(config.projectName)", systemImage: "hammer") {
                    MenuBarView()
                        .environment(viewModel)
                }

                Settings {
                    SettingsView()
                        .environment(viewModel)
                }
            }
        }
        """
        try appFile.write(
            to: destination.appendingPathComponent("Sources/\(config.projectName)/\(config.projectName)App.swift"),
            atomically: true,
            encoding: .utf8
        )

        let contentView = """
        import SwiftUI

        struct ContentView: View {
            @Environment(AppViewModel.self) private var viewModel

            var body: some View {
                @Bindable var viewModel = viewModel

                NavigationSplitView {
                    List {
                        Text("Sidebar")
                    }
                    .navigationTitle(viewModel.title)
                } detail: {
                    VStack {
                        Image(systemName: "hammer")
                            .imageScale(.large)
                            .foregroundStyle(.tint)
                        Text("Hello, macOS!")
                    }
                    .padding()
                }
                .accessibilityIdentifier("content_view")
            }
        }

        #Preview {
            ContentView()
                .environment(AppViewModel())
        }
        """
        try contentView.write(
            to: destination.appendingPathComponent("Sources/\(config.projectName)/Views/ContentView.swift"),
            atomically: true,
            encoding: .utf8
        )

        let menuBarViewContent = """
        import SwiftUI

        struct MenuBarView: View {
            @Environment(AppViewModel.self) private var viewModel

            var body: some View {
                VStack(alignment: .leading) {
                    Text(viewModel.title)
                        .font(.headline)
                    Divider()
                    Button("Open Main Window") {
                        NSApp.activate(ignoringOtherApps: true)
                    }
                    Button("Quit") {
                        NSApp.terminate(nil)
                    }
                }
                .padding()
                .frame(width: 200)
            }
        }

        #Preview {
            MenuBarView()
                .environment(AppViewModel())
        }
        """
        try menuBarViewContent.write(
            to: destination.appendingPathComponent("Sources/\(config.projectName)/MenuBar/MenuBarView.swift"),
            atomically: true,
            encoding: .utf8
        )

        let settingsView = """
        import SwiftUI

        struct SettingsView: View {
            @State private var apiEndpoint = "https://api.example.com"
            @State private var enableTelemetry = true

            var body: some View {
                Form {
                    Section("Network") {
                        TextField("API Endpoint", text: $apiEndpoint)
                    }
                    Section("Privacy") {
                        Toggle("Enable Telemetry", isOn: $enableTelemetry)
                    }
                }
                .padding()
                .frame(width: 400, height: 200)
            }
        }

        #Preview {
            SettingsView()
        }
        """
        try settingsView.write(
            to: destination.appendingPathComponent("Sources/\(config.projectName)/Settings/SettingsView.swift"),
            atomically: true,
            encoding: .utf8
        )

        let viewModelContent = """
        import Foundation
        import Observation

        @Observable
        final class AppViewModel {
            var title: String = "\(config.projectName)"

            init() {}
        }
        """
        try viewModelContent.write(
            to: destination.appendingPathComponent("Sources/\(config.projectName)/ViewModels/AppViewModel.swift"),
            atomically: true,
            encoding: .utf8
        )

        let modelContent = """
        import Foundation

        struct AppModel: Codable, Sendable {
            let id: UUID
            var name: String

            init(id: UUID = UUID(), name: String) {
                self.id = id
                self.name = name
            }
        }
        """
        try modelContent.write(
            to: destination.appendingPathComponent("Sources/\(config.projectName)/Models/AppModel.swift"),
            atomically: true,
            encoding: .utf8
        )

        let serviceContent = """
        import Foundation
        #if canImport(AnvilNetwork)
        import AnvilNetwork
        #endif

        protocol NetworkServiceProtocol: Sendable {
            func fetchData() async throws -> Data
        }

        actor NetworkService: NetworkServiceProtocol {
            func fetchData() async throws -> Data {
                #if canImport(AnvilNetwork)
                // Use AnvilNetwork when available
                #endif
                return Data()
            }
        }
        """
        try serviceContent.write(
            to: destination.appendingPathComponent("Sources/\(config.projectName)/Services/NetworkService.swift"),
            atomically: true,
            encoding: .utf8
        )
    }

    private func generateIOSSourceStructure(at destination: URL, config: ProjectConfig) throws {
        // App entry point
        let appFile = """
        import SwiftUI

        public struct \(config.projectName)RootView: View {
            public init() {}

            public var body: some View {
                ContentView()
            }
        }
        """
        try appFile.write(
            to: destination.appendingPathComponent("Sources/\(config.projectName)/\(config.projectName)App.swift"),
            atomically: true,
            encoding: .utf8
        )

        // ContentView
        let contentView = """
        import SwiftUI

        struct ContentView: View {
            var body: some View {
                VStack {
                    Image(systemName: "globe")
                        .imageScale(.large)
                        .foregroundStyle(.tint)
                    Text("Hello, world!")
                }
                .padding()
                .accessibilityIdentifier("content_view")
            }
        }

        #Preview {
            ContentView()
        }
        """
        try contentView.write(
            to: destination.appendingPathComponent("Sources/\(config.projectName)/Views/ContentView.swift"),
            atomically: true,
            encoding: .utf8
        )

        // ViewModel
        let viewModel = """
        import Foundation
        import Observation

        @Observable
        final class AppViewModel {
            var title: String = "\(config.projectName)"

            init() {}
        }
        """
        try viewModel.write(
            to: destination.appendingPathComponent("Sources/\(config.projectName)/ViewModels/AppViewModel.swift"),
            atomically: true,
            encoding: .utf8
        )

        // Model
        let model = """
        import Foundation

        struct AppModel: Codable, Sendable {
            let id: UUID
            var name: String

            init(id: UUID = UUID(), name: String) {
                self.id = id
                self.name = name
            }
        }
        """
        try model.write(
            to: destination.appendingPathComponent("Sources/\(config.projectName)/Models/AppModel.swift"),
            atomically: true,
            encoding: .utf8
        )

        // Service
        let service = """
        import Foundation

        protocol NetworkServiceProtocol: Sendable {
            func fetchData() async throws -> Data
        }

        actor NetworkService: NetworkServiceProtocol {
            func fetchData() async throws -> Data {
                return Data()
            }
        }
        """
        try service.write(
            to: destination.appendingPathComponent("Sources/\(config.projectName)/Services/NetworkService.swift"),
            atomically: true,
            encoding: .utf8
        )
    }

    private func generateTestStructure(at destination: URL, config: ProjectConfig) async throws {
        if config.includeUnitTests {
            let unitTests: String
            if config.isMacOSApp {
                unitTests = """
                import Testing
                @testable import \(config.projectName)

                struct \(config.projectName)Tests {
                    @Test func modelCreation() async throws {
                        let model = AppModel(name: "Test")
                        #expect(model.name == "Test")
                    }

                    @Test func viewModelTitle() async throws {
                        let viewModel = AppViewModel()
                        #expect(viewModel.title == "\(config.projectName)")
                    }
                }
                """
            } else {
                unitTests = """
                import Testing
                @testable import \(config.projectName)

                struct \(config.projectName)Tests {
                    @Test func example() async throws {
                        let model = AppModel(name: "Test")
                        #expect(model.name == "Test")
                    }
                }
                """
            }
            try unitTests.write(
                to: destination.appendingPathComponent("Tests/\(config.projectName)Tests/\(config.projectName)Tests.swift"),
                atomically: true,
                encoding: .utf8
            )
        }

        if config.includeUITests && !config.isMacOSApp {
            let uiTests = """
            import XCTest

            final class \(config.projectName)UITests: XCTestCase {
                func testExample() throws {
                    let app = XCUIApplication()
                    app.launch()
                    XCTAssertTrue(app.otherElements["content_view"].exists)
                }
            }
            """
            try uiTests.write(
                to: destination.appendingPathComponent("Tests/\(config.projectName)UITests/\(config.projectName)UITests.swift"),
                atomically: true,
                encoding: .utf8
            )
        }
    }

    private func generateAccessibilityEnforcement(at destination: URL, config: ProjectConfig) async throws {
        let helper = """
        import SwiftUI

        /// Accessibility helper for consistent identifier patterns
        enum AccessibilityIdentifier {
            static func view(_ name: String) -> String { "view_\\(name)" }
            static func button(_ name: String) -> String { "btn_\\(name)" }
            static func textField(_ name: String) -> String { "tf_\\(name)" }
            static func list(_ name: String) -> String { "list_\\(name)" }
            static func cell(_ name: String) -> String { "cell_\\(name)" }
        }

        extension View {
            func withAccessibilityID(_ identifier: String) -> some View {
                self.accessibilityIdentifier(identifier)
            }
        }
        """
        try helper.write(
            to: destination.appendingPathComponent("Sources/\(config.projectName)/Utilities/AccessibilityHelper.swift"),
            atomically: true,
            encoding: .utf8
        )
    }

    private func generateLocalizationInfrastructure(at destination: URL, config: ProjectConfig) async throws {
        let languages = config.targetLanguages

        var localizations: [String: [String: Any]] = [:]
        for lang in languages {
            localizations[lang] = [
                "stringUnit": [
                    "state": "translated",
                    "value": "Hello, world!"
                ]
            ]
        }

        let stringsDict: [String: Any] = [
            "sourceLanguage": languages.first ?? "en",
            "strings": [
                "hello_world": [
                    "localizations": localizations
                ]
            ],
            "version": "1.0"
        ]

        let jsonData = try JSONSerialization.data(withJSONObject: stringsDict, options: .prettyPrinted)
        let resourcesDir = destination.appendingPathComponent("Sources/\(config.projectName)/Resources")
        try fileManager.createDirectory(at: resourcesDir, withIntermediateDirectories: true)
        try jsonData.write(to: resourcesDir.appendingPathComponent("Localizable.xcstrings"))
    }

    private func generateGitHooks(at destination: URL, config: ProjectConfig) async throws {
        let preCommit = """
        #!/bin/sh
        # Pre-commit hook — Generated by SwiftAnvil
        set -e

        echo "Running pre-commit checks..."

        if command -v swiftlint >/dev/null 2>&1; then
            echo "Running SwiftLint..."
            swiftlint lint --strict
        fi

        if command -v swiftformat >/dev/null 2>&1; then
            echo "Running SwiftFormat..."
            swiftformat --lint .
        fi

        echo "Building..."
        swift build

        echo "Running tests..."
        swift test

        echo "Pre-commit checks passed."
        """

        let hooksDir = destination.appendingPathComponent(".git/hooks")
        try fileManager.createDirectory(at: hooksDir, withIntermediateDirectories: true)
        let hookPath = hooksDir.appendingPathComponent("pre-commit")
        try preCommit.write(to: hookPath, atomically: true, encoding: .utf8)

        // Make executable
        try fileManager.setAttributes([.posixPermissions: 0o755], ofItemAtPath: hookPath.path)
    }

    private func generateCIWorkflows(at destination: URL, config: ProjectConfig) async throws {
        let workflow = """
        name: CI

        on:
          push:
            branches: [main, develop]
          pull_request:
            branches: [main, develop]

        jobs:
          test:
            runs-on: macos-latest
            steps:
              - uses: actions/checkout@v6
              - name: Build
                run: swift build
              - name: Test
                run: swift test
        """

        let workflowsDir = destination.appendingPathComponent(".github/workflows")
        try fileManager.createDirectory(at: workflowsDir, withIntermediateDirectories: true)
        try workflow.write(
            to: workflowsDir.appendingPathComponent("ci.yml"),
            atomically: true,
            encoding: .utf8
        )
    }

    private func generateDocumentationRegistry(at destination: URL, config: ProjectConfig) async throws {
        let registry = """
        documents:
          readme:
            path: "README.md"
            sources: []
        """

        let docsDir = destination.appendingPathComponent("Documentation/Registry")
        try fileManager.createDirectory(at: docsDir, withIntermediateDirectories: true)
        try registry.write(
            to: docsDir.appendingPathComponent("index.yml"),
            atomically: true,
            encoding: .utf8
        )
    }

    private func generateImmunityConfig(at destination: URL, config: ProjectConfig) async throws {
        let config = """
        {
          "enabled": true,
          "telemetry": {
            "buildMetrics": true,
            "testMetrics": true,
            "coverageMetrics": true
          }
        }
        """

        try config.write(
            to: destination.appendingPathComponent(".foundation/immunity.json"),
            atomically: true,
            encoding: .utf8
        )
    }

    private func generateAgentsMD(at destination: URL, config: ProjectConfig) async throws {
        let architecture = config.isMacOSApp
            ? """
        - **Pattern**: MVVM + MenuBar + Settings
        - **Framework**: SwiftUI (macOS 15+)
        - **Scenes**: WindowGroup + MenuBarExtra + Settings
        - **Package Manager**: Swift Package Manager
        """
            : """
        - **Pattern**: MVVM + I/O
        - **Framework**: SwiftUI
        - **Package Manager**: Swift Package Manager
        """

        let agentsMD = """
        # \(config.projectName) — Agent Guidelines

        ## Project Overview

        This project was scaffolded with **SwiftAnvil**.

        ## Architecture

        \(architecture)

        ## Key Principles

        1. Host Agnosticism
        2. SOLID principles
        3. Accessibility First
        4. Localization Ready
        5. Test Coverage

        ## Development Workflow

        ```bash
        swift build
        swift test
        swiftlint lint
        ```
        """

        try agentsMD.write(
            to: destination.appendingPathComponent("AGENTS.md"),
            atomically: true,
            encoding: .utf8
        )
    }
}

enum GenerationError: Error, CustomStringConvertible {
    case destinationExists(String)
    case templateNotFound(String)
    case invalidConfiguration(String)

    var description: String {
        switch self {
        case .destinationExists(let path):
            return "Destination already exists: \(path)"
        case .templateNotFound(let name):
            return "Template not found: \(name)"
        case .invalidConfiguration(let reason):
            return "Invalid configuration: \(reason)"
        }
    }
}
